### ISSUE TITLE
Parsing issues with updates not delivered in Markdown format

### ISSUE THREAD

**Issue by michi-onl** [helldivers-2/diveharder_api.py#2]
#### Description:
Previously, updates were delivered in Markdown format, and I used `react-markdown` to render them. However, the recent updates are not in Markdown format, and `react-markdown` is unable to parse them correctly.

#### Example of the new format:
Good day!\nHot Fix for a crash introduced in yesterdays rollout!\nCarry on liberating soldiers.\n\n[b]Fixes[/b]\n[list]\n[*] Fix for a common crash which occurred when accessing the Acquisitions menu\n[/list]\n\n[b]Known Issues (Unchanged from patch 1.000.200)[/b]\nThese are issues that were either introduced by this patch and are being worked on, or are from a previous version and have not yet been fixed.\n\n[list]\n[*] Game might crash when picking up a snowball or throwing back a grenade\n[*] Various issues involving friend invites and cross-play:\n[*] Cross-platform friend invites might not show up in the Friend Requests tab.\n[*] Players cannot unfriend other players befriended via friend code.\n[*] Players cannot unblock players that

#### Expected behavior:
The updates should be delivered in a format that `react-markdown` can parse correctly, allowing us to render them properly on the UI.

#### Actual behavior:
The updates are not in Markdown format, causing `react-markdown` to fail to parse them correctly, and resulting in rendering issues on the UI.

#### Steps to reproduce:
1. Visit https://www.helldiverscompanion.app/
2. Scroll to recent Updates
3. Click on "Read more"

#### Environment:
- Next.js v14

#### Additional information:
![screen 305](https://github.com/helldivers-2/diveharder_api.py/assets/87752300/fb4ca927-227f-4eaf-9ea9-cab548c2f5a4)

**Comment by chatterchats** [comment]
Parsing reimplemented. My apologies about that!
