### ISSUE TITLE
Error fetching newsFeed from API

### ISSUE THREAD

**Issue by michi-onl** [helldivers-2/diveharder_api.py#3]
### Description
When attempting to fetch an API in a Next.js TypeScript application, I am encountering an error with the response:

```json
"newsFeed":{
	"errorCode":0,
	"traceId":"0HN28UQ8VP33E:00000001",
	"message":"Model validation failed: The value '1024?maxEntries=1024' is not valid."
	}
```

### Steps to Reproduce
- Search for newsFeed.message on https://api.diveharder.com/all

### Expected Behavior
The API should successfully return data from the specified endpoint without any validation errors.

### Environment
Next.js version: 14

### Additional Context
The query parameter ?maxEntries=1024 seems to be causing an issue with the server's validation.

![screen 306](https://github.com/helldivers-2/diveharder_api.py/assets/87752300/102682bf-01f9-4299-a0f9-cd71f19e2fe4)

**Comment by chatterchats** [comment]
My apologies, fix deployed. Had a setting wrong on the host side smh.
